### ISSUE TITLE
Git commit fails when using commit signing

### ISSUE THREAD

**Issue by 0mega** [git-duet/git-duet#50]
After enabling the [commit signing feature](https://help.github.com/articles/signing-commits-using-gpg/) the git duet-commit stopped working :(

**Comment by jszwedko** [comment]
Hi @0mega,

I believe you are seeing an issue when using `git duet` because it will attempt to use the GPG key associated with the committer rather than the author (which is the default for `git commit` without signoff since, in that case, the author _is_ the committer). If I use `git duet foo bar`, where I have have the key for the email for `bar` in my GPG keyring, it appears to function as expected.

Is it possible that you don't have the GPG key for the assigned committer in your keyring?

**Comment by 0mega** [comment]
@jszwedko thank you, you are absolutely right. Sorry for replying so late. This is not an issue, closing.

**Comment by technicalpickles** [comment]
I ran into this recently while pairing, and I was using my handle as the second name.

Would it be possible to detect if there's a key  (ssh key for me, since it's supported now) for one of the users, and to use that one as the author?
