### ISSUE TITLE
Start using the "Co-authored-by" trailer

### ISSUE THREAD

**Issue by dylnclrk** [git-duet/git-duet#56]
Github just announced support for a `Co-authored-by:` trailer. 
Perhaps git-duet could use it instead of `Signed-off-by:`.

See: https://github.com/blog/2496-commit-together-with-co-authors

**Comment by dylnclrk** [comment]
I just started looking into this and it seems more complicated than `s/Signed-off-by/Co-authored-by`

**Comment by jszwedko** [comment]
Oh wow, very cool. I could see this sort of "defacto" standard morphing into something `git` supports natively some day.

We should definitely implement this with opt-in configuration. Unfortunately, as you note, it isn't as simple as copy/paste/sed since the current implementation uses the native support for "committers", but it shouldn't be too tricky to add.

I'll attempt to get to this soon, but I welcome a PR if someone wants to get this rolling.

Thanks for raising this up @dylnclrk !

**Comment by dideler** [comment]
> I could see this sort of "defacto" standard morphing into something git supports natively some day.

Note that Git is aware of it, but support seems limited right now.

See https://twitter.com/niik/status/958417974620286977 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=451880 for more info.

**Comment by dylnclrk** [comment]
rad @ansd 🤘
