### ISSUE TITLE
Co-Authored-By Fails if prepare-commit-msg already exists

### ISSUE THREAD

**Issue by JohnAJimenez** [git-duet/git-duet#74]
If you already have a prepare-commit-msg file from another tool (example if you are using git-tracker) then the Co-Authored-By functionality fails with error message:
```
can't install hook: file [path-removed]/.git/hooks/prepare-commit-msg already exists
exit status 1
```
We have worked around this by manually adding the expected contents from git-duet into the existing file.

Once I can get the Go environment set up locally, I will take a stab at updating the code. My high level idea is: instead of failing if the file exists, try to read the file looking for our payload and adding it at the bottom if needed.

**Comment by jszwedko** [comment]
:+1: thanks @JohnAJimenez 

One consideration is that `git-duet` uses bash where the prepare-commit-msg hook could be any executable file. If we want to append, we should check that the existing script is using bash. Otherwise perhaps we could just output the text that `git-duet` wants to add and ask that the user combine it with their existing prepare-commit-msg hook.

**Comment by Kehrlann** [comment]
I'd like to pick that one up !

I'm thinking of the following message, for example for prepare-commit-msg :

```
It seems you already have a "prepare-commit-msg" hook.
To enable the git-duet hook, please append:
  
  exec git duet-prepare-commit-msg "$@"

to your .git/hooks/prepare-commit-msg file.
```

In addition to this, it could be interesting to explain to the user why this message shows up, but maybe this could be covered in another issue.

Thoughts ?
