### ISSUE TITLE
Update Git version in tests, fix broken tests

### ISSUE THREAD

**Issue by rafecolton** [git-duet/git-duet#92]
As described in https://github.com/git-duet/git-duet/pull/91, update git to 2.28.0 in test docker container, or at least 2.27 to, match Travis, then fix broken tests.

**Comment by jials** [comment]
Hi there! I did a quick spike on this issue and found out that the problem originates from this particular [change](https://github.com/git/git/blob/master/Documentation/RelNotes/2.26.0.txt#L9-L17) introduced in `git v2.26.0`:
```
"git rebase" uses a different backend that is based on the 'merge'
   machinery by default.  There are a few known differences in the
   behaviour from the traditional machinery based on patch+apply.
```

Should we change the expectation of the test case to `writes Co-authored-by trailer when rebasing if GIT_DUET_CO_AUTHORED_BY` instead?

**Comment by rafecolton** [comment]
@jials thanks for taking a look at this! Can you please provide a little more detail? Specifically, what's the expectation in the current test and how is the behavior changed based on the change you linked?

Thank you!

**Comment by jials** [comment]
Currently there are two test cases failing after upgrading to `git` > `v2.26.0`:
- [does not write Co-authored-by trailer when rebasing if GIT_DUET_CO_AUTHORED_BY](https://github.com/git-duet/git-duet/blob/master/test/git-duet.bats#L286-L290)
- [as duet: does not write Co-authored-by trailer when rebasing if GIT_DUET_CO_AUTHORED_BY](https://github.com/git-duet/git-duet/blob/master/test/git-as.bats#L488-L492)

Before `git v2.26.0`, doing a rebase does not invoke the `prepare-commit-msg` hook, hence the expected behavior is to not add the additional `Co-authored-by` trailer.

However, since `git v2.26.0`, git changed the `git rebase` mechanism to use the `merge` instead of `apply`, which is causing the `prepare-commit-msg` hook to be invoked during rebase. As the result, the `Co-authored-by` trailer is also appended (only once if it does not exist) during rebase, causing the existing test cases to fail as it is expecting no `Co-authored-by` trailer.

**Comment by rafecolton** [comment]
Hm, what kind of rebase is this tested for - a fast-forward or an interactive? Although either way, I don't think we'd want to rewrite the commit message. If it is interactive, we could maybe allow changes if the user selects `e` and actually makes new commits. I'm not sure how we would test for that though - send/expect? Probably not worth the effort. In the documentation you linked, it says:

> After [emailing them], you can set the 'rebase.backend' configuration variable to 'apply', in order to use the old default behaviour in the meantime.

Perhaps we want to set this value in order to keep the existing behavior. What do you think @jszwedko?

**Comment by jials** [comment]
@rafecolton Got it. I have raised the PR to set `rebase.backend` to `apply` for the failing test cases while working on a long-term fix. 🚀

**Comment by rafecolton** [comment]
Fixed in https://github.com/git-duet/git-duet/pull/93, thanks @jials!
